# Generated by Django 4.2.6 on 2024-02-23 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Home', '0003_partner_sign_up'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Profile_Pic', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('First_Name', models.CharField(max_length=255)),
                ('Last_Name', models.CharField(max_length=255)),
                ('Email', models.CharField(max_length=255)),
                ('Location', models.CharField(blank=True, max_length=255, null=True)),
                ('Phone', models.CharField(blank=True, max_length=20, null=True)),
                ('Gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True)),
                ('DOB', models.DateField(blank=True, null=True)),
                ('about', models.TextField(blank=True, null=True)),
                ('Student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Home.students_sign_up')),
            ],
        ),
    ]
