# Generated by Django 4.2.6 on 2024-02-25 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resumes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Resume', models.FileField(upload_to='resumes/')),
            ],
        ),
    ]
