# Generated by Django 4.2.6 on 2024-02-29 11:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeHeadline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('Resume_headline_data', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Projectdetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('Project_Name', models.CharField(max_length=150)),
                ('Project_Start_Month', models.CharField(max_length=100)),
                ('Project_Start_Year', models.IntegerField()),
                ('Project_End_Month', models.CharField(max_length=100)),
                ('Project_End_Year', models.IntegerField()),
                ('Project_Desc', models.TextField()),
                ('Project_Url', models.CharField(max_length=150)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Internshipdetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('Intern_Company_Name', models.CharField(max_length=150)),
                ('Intern_Start_Month', models.CharField(max_length=100)),
                ('Intern_Start_Year', models.IntegerField()),
                ('Intern_End_Month', models.CharField(max_length=100)),
                ('Intern_End_Year', models.IntegerField()),
                ('Intern_Project_Name', models.CharField(max_length=255)),
                ('Intern_Desc', models.TextField()),
                ('Intern_Project_Url', models.CharField(max_length=150)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmploymentDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('Exp_Year', models.IntegerField()),
                ('Exp_Month', models.CharField(max_length=100)),
                ('Work_Company_Name', models.CharField(max_length=150)),
                ('Work_Designation', models.CharField(max_length=100)),
                ('Work_start_Month', models.CharField(max_length=100)),
                ('Work_start_Year', models.IntegerField()),
                ('Work_End_Month', models.CharField(max_length=100)),
                ('Work_End_Year', models.IntegerField()),
                ('Work_Desc', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Educationdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('College_Name', models.CharField(max_length=255)),
                ('College_Start_Year', models.IntegerField()),
                ('College_End_Year', models.IntegerField()),
                ('Degree', models.CharField(max_length=100)),
                ('Stream', models.CharField(max_length=100)),
                ('Grading_System', models.CharField(max_length=10)),
                ('Performance', models.CharField(max_length=20)),
                ('Course_Type', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Competitivedetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('Competitive_Name', models.CharField(max_length=150)),
                ('Competitive_score', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Communication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('Communication_Language', models.CharField(max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Certificatedetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('Certificate_Name', models.CharField(max_length=150)),
                ('Certificate_ID', models.CharField(max_length=100)),
                ('Certificate_URL', models.CharField(max_length=100)),
                ('Certificate_start_Month', models.CharField(max_length=100)),
                ('Certificate_start_Year', models.IntegerField()),
                ('Certificate_End_Month', models.CharField(max_length=100)),
                ('Certificate_End_Year', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AwardDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('work_desc', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AcadmicDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('Acadmic_desc', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
