# Generated by Django 4.2.6 on 2024-02-20 20:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='instructors_sign_up',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('Full_Name', models.CharField(max_length=255)),
                ('Phone', models.CharField(max_length=12)),
                ('Email', models.EmailField(max_length=255)),
                ('Password', models.CharField(max_length=255)),
            ],
        ),
    ]
