# Generated by Django 4.2.6 on 2024-02-21 03:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_instructors_sign_up'),
    ]

    operations = [
        migrations.CreateModel(
            name='partner_sign_up',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('Organigation_Name', models.CharField(max_length=255)),
                ('Admin_Administrator', models.CharField(max_length=255)),
                ('Phone', models.CharField(max_length=255)),
                ('Email', models.EmailField(max_length=255)),
                ('Password', models.CharField(max_length=255)),
            ],
        ),
    ]
